/**
 * services/reportService.js
 * ============================================================
 * MODULE 7 (PDF layer) — Renders the security report to PDF.
 * Uses PDFKit to build a streamable document the controller
 * pipes straight to the HTTP response. Renders the structured
 * `reportData` produced by reportGenerator.js (overall score,
 * per-module risk levels + timestamps, recommendations).
 */
import PDFDocument from 'pdfkit';

/**
 * @param {object} opts
 *   - report: persisted Report doc (or a {_id,title} stub)
 *   - scans:  raw ScanHistory docs (recent activity list)
 *   - reportData: structured report from buildReport()
 */
export const buildPdfReport = ({ report = {}, scans = [], reportData }) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Header
  doc.fontSize(22).text('Cyber Security Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(10).fillColor('#666').text(`Generated: ${new Date().toISOString()}`, { align: 'center' });
  doc.moveDown(2);

  // ---- Overall score + risk level ----
  if (reportData) {
    doc.fontSize(14).fillColor('#000').text('Overall Security Posture');
    doc.fontSize(12).text(`Security Score: ${reportData.securityScore}/100`);
    doc.text(`Overall Risk Level: ${reportData.overallRiskLevel}`);
    doc.text(`Total Scans: ${reportData.totalScans}`);
    doc.text(`Threats Detected: ${reportData.threatsDetected}`);
    doc.moveDown();

    // ---- Module-wise results ----
    doc.fontSize(14).text('Module-wise Results');
    reportData.modules.forEach((m) => {
      doc.fontSize(12).text(`• ${m.label}`);
      doc.fontSize(10).fillColor('#444')
        .text(`  Scans: ${m.scans} | Avg Threat: ${m.avgThreatScore}/100 | Risk: ${m.riskLevel}` +
          (m.latestScan ? ` | Last: ${new Date(m.latestScan).toLocaleString()}` : ''));
      doc.fillColor('#000');
    });
    doc.moveDown(2);

    // ---- Recommendations ----
    doc.fontSize(14).text('Recommendations');
    reportData.recommendations.forEach((r) => doc.fontSize(11).text(`• ${r}`));
    doc.moveDown(2);
  } else {
    // Legacy fallback (keeps old callers working).
    const { summary = {}, moduleBreakdown = {} } = report;
    doc.fontSize(14).text('Summary');
    doc.fontSize(12).text(`Total Scans: ${summary.totalScans ?? 0}`);
    doc.text(`Threats Detected: ${summary.threatsDetected ?? 0}`);
    doc.moveDown();
    doc.fontSize(14).text('Module Breakdown');
    Object.entries(moduleBreakdown).forEach(([k, v]) =>
      doc.fontSize(12).text(`• ${k.toUpperCase()}: ${v.count} scans (avg risk ${v.avg})`));
    doc.moveDown(2);
  }

  // ---- Recent scan activity (timestamps) ----
  doc.fontSize(14).text('Recent Scan Activity');
  doc.fontSize(10);
  scans.slice(0, 30).forEach((s) => {
    const ts = s.createdAt ? new Date(s.createdAt).toLocaleString() : 'n/a';
    doc.text(`[${ts}] ${String(s.type || '').toUpperCase()} — ${s.verdict} (risk ${s.riskScore})`);
  });

  // Footer
  doc.moveDown();
  doc.fontSize(9).fillColor('#999')
    .text('Generated by Cyber Security Assistant. This report is confidential.', { align: 'center' });
  return doc;
};

export default { buildPdfReport };
